image: 'Visual Studio 2017'

configuration:
  - Release

environment:
  ARTIFACT_PATH: cutter-deps-win-x86_64.tar.gz
  ARTIFACT_NAME: cutter-deps-win-x86_64.tar.gz

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - C:\msys64\usr\bin\bash -lc "
    wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/LLVM-10.0.0-win64.exe &&
    7z x -oLLVM LLVM-10.0.0-win64.exe &&
    export LLVM_INSTALL_DIR=\"$PWD/LLVM\" &&
    cd \"%APPVEYOR_BUILD_FOLDER%\" &&
    export PATH=\"$PWD/qt/bin:$LLVM_INSTALL_DIR/bin:$PATH\" &&
    make PYTHON_WINDOWS=\"C:\Python36-x64\""

artifacts:
  - path: "%ARTIFACT_PATH%"
    name: "%ARTIFACT_NAME%"

deploy:
  description: "cutter-deps"
  provider: GitHub
  auth_token:
    secure: KmbKdGN8lEOX7By1hNkfGu7iNA+CVztc2qIO/BPXykFXeeKx6+XQBKgIIq9hDorS
  artifact: "%ARTIFACT_PATH%"
  on:
    APPVEYOR_REPO_TAG: true
