name: package build

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    if: false
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: build linux outputs
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential \
                             libclang-11-dev \
                             llvm-11 \
                             cmake \
                             curl
        make
        echo UPLOAD_FILE=cutter-deps-linux-x86_64.tar.gz >> $GITHUB_ENV
        echo UPLOAD_ASSET_TYPE=application/gzip >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.UPLOAD_FILE }}
        path: ${{ env.UPLOAD_FILE }}
    - name: Get release
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: get_release
      uses: karliss/get-release@bee343636450eb2e9b85d9f1592d8d73c408dc74
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release assets
      if: steps.get_release.outputs.upload_url != null
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_FILE }}
          asset_name: ${{ env.UPLOAD_FILE }}
          asset_content_type: ${{ env.UPLOAD_ASSET_TYPE }}
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: VSSetup
      shell: cmd
      run: |
        pwd
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        pwd
        call C:/shells/msys2bash.cmd "which cl.exe"
    - name: build windows outputs
      shell: 'C:/shells/msys2bash.cmd {0}'
      run: |
        set -euo pipefail
        which cl.exe
        make
        
    - name: set windows outputs
      shell: bash
      run: |
        echo UPLOAD_FILE=cutter-deps-windows-x86_64.tar.gz >> $GITHUB_ENV
        echo UPLOAD_ASSET_TYPE=application/gzip >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.UPLOAD_FILE }}
        path: ${{ env.UPLOAD_FILE }}
    - name: Get release
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: get_release
      uses: karliss/get-release@bee343636450eb2e9b85d9f1592d8d73c408dc74
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release assets
      if: steps.get_release.outputs.upload_url != null
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_FILE }}
          asset_name: ${{ env.UPLOAD_FILE }}
          asset_content_type: ${{ env.UPLOAD_ASSET_TYPE }}
  build-macos:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
              macos-x86_64,
              macos-arm64,
            ]
        include:
          - name: macos-x86_64
            os: macos-11
            arch: x86_64
          - name: macos-arm64
            os: macos-14
            arch: arm64
    steps:
    - uses: actions/checkout@v3
    - name: build macos
      run: |
        set -euo pipefail
        brew install llvm ccache
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          export CMAKE_PREFIX_PATH="$HOMEBREW_PREFIX/opt/llvm";
        else
          export CMAKE_PREFIX_PATH="/usr/local/opt/llvm";
        fi
        echo "###### Applications ######"
        ls /Applications
        echo "###### XCode Info ######"
        sudo xcode-select --reset
        export BUILD_SDK_PATH=$(xcrun --show-sdk-path)
        echo "$BUILD_SDK_PATH"
        echo "###### xcode-select Info ######"
        xcode-select -print-path
        which clang
        brew info llvm
        echo "###### Make ######"
        export MACOSX_DEPLOYMENT_TARGET=11.0
        export MIN_SUPPORTED_MACOSX_DEPLOYMENT_TARGET=11.0
        export CFLAGS=" -isysroot $BUILD_SDK_PATH "
        export CCFLAGS=" -isysroot $BUILD_SDK_PATH "
        export CXXFLAGS=" -isysroot $BUILD_SDK_PATH "
        make
        echo UPLOAD_FILE=cutter-deps-macos-${{ matrix.arch }}.tar.gz >> $GITHUB_ENV
        echo UPLOAD_ASSET_TYPE=application/gzip >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.UPLOAD_FILE }}
        path: ${{ env.UPLOAD_FILE }}
    - name: Get release
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: get_release
      uses: karliss/get-release@bee343636450eb2e9b85d9f1592d8d73c408dc74
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release assets
      if: steps.get_release.outputs.upload_url != null
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_FILE }}
          asset_name: ${{ env.UPLOAD_FILE }}
          asset_content_type: ${{ env.UPLOAD_ASSET_TYPE }}
