name: package build

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: build linux
      shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get -qqy update
        apt-get -qqy install build-essential \
                             libclang-8-dev \
                             llvm-8 \
                             libglib2.0-dev \
                             mesa-common-dev \
                             libgl1-mesa-dev \
                             zlib1g-dev \
                             libpcre2-dev \
                             cmake \
                             curl \
                             wget
        make
        echo UPLOAD_FILE=cutter-deps-linux-x86_64.tar.gz >> $GITHUB_ENV
        echo UPLOAD_ASSET_TYPE=application/gzip >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.UPLOAD_FILE }}
        path: ${{ env.UPLOAD_FILE }}
    - name: Get release
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: get_release
      uses: karliss/get-release@bee343636450eb2e9b85d9f1592d8d73c408dc74
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release assets
      if: steps.get_release.outputs.upload_url != null
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_FILE }}
          asset_name: ${{ env.UPLOAD_FILE }}
          asset_content_type: ${{ env.UPLOAD_ASSET_TYPE }}

  build-macos:
    runs-on: macos-11
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: build macos
      run: |
        set -euo pipefail
        brew install llvm ccache
        export PATH="/usr/local/opt/llvm/bin:$PATH";
        echo "###### Applications ######"
        ls /Applications
        echo "###### XCode Info ######"
        sudo xcode-select --reset
        export BUILD_SDK_PATH=$(xcrun --show-sdk-path)
        echo "$BUILD_SDK_PATH"
        echo "###### xcode-select Info ######"
        xcode-select -print-path
        echo "###### LLVM Info ######"
        which llvm-config
        llvm-config --version
        echo "###### Make ######"
        export MACOSX_DEPLOYMENT_TARGET=11.0
        export MIN_SUPPORTED_MACOSX_DEPLOYMENT_TARGET=11.0
        export CFLAGS=" -isysroot $BUILD_SDK_PATH "
        export CCFLAGS=" -isysroot $BUILD_SDK_PATH "
        export CXXFLAGS=" -isysroot $BUILD_SDK_PATH "
        sudo rm -rf /Library/Developer/CommandLineTools
        make
        echo UPLOAD_FILE=cutter-deps-macos-x86_64.tar.gz >> $GITHUB_ENV
        echo UPLOAD_ASSET_TYPE=application/gzip >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.UPLOAD_FILE }}
        path: ${{ env.UPLOAD_FILE }}
    - name: Get release
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: get_release
      uses: karliss/get-release@bee343636450eb2e9b85d9f1592d8d73c408dc74
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release assets
      if: steps.get_release.outputs.upload_url != null
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_FILE }}
          asset_name: ${{ env.UPLOAD_FILE }}
          asset_content_type: ${{ env.UPLOAD_ASSET_TYPE }}
